---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: samayochita
  become: false
  
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "samayochita/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
   
    - name: Running container
      shell: docker run -it -d --name calculator samayochita/calculator
